services:
  app:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php_image_edit
    volumes:
      - ./app:/app
    ports:
      - "8001:8001"
    # depends_on:
    #   - db

  # db:
  #   build:
  #     context: .
  #     dockerfile: mysql.dockerfile
  #   container_name: mysql_container
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #   ports:
  #     - "33066:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql

# volumes:
#   db_data:
